
Struct.new("Skill", :name, :ability, :ranks, :misc, :class, :trained_only)

h = Hash.new(0)


File.open("Skills.tex", "r") do |l|
  while (li = l.gets)
    if (li =~ /^\\skill\{([^}]+)\}\s*\{([^\}]+)\}\{([^\}]+)\}\{([^\}]+)\}\{([^\}]+)\}\{([^\}]+)\}$/)
      skl = Struct::Skill.new()
      skl[:name] = $1
      skl[:ability] = $2
      skl[:ranks] = $3
      skl[:misc] = $4
      skl[:class] = $5
      skl[:trained_only] = $6
      h[$1] = skl
    end
  end
end

Dir.glob('*').select {|f| File.directory? f}.select {|f| File.exists? f + "/Skills.tex"}.each do |d|
  fName = d + "/Skills.tex"
  File.open(fName , "r") do |l|
    while (li = l.gets)
      if (li =~ /^\\skill\{([^}]+)\}\s*\{([^\}]+)\}\{([^\}]+)\}\{([^\}]+)\}\{([^\}]+)\}\{([^\}]+)\}$/)
        h[$1][:misc] = $4
      end
    end
  end
  File.open(fName, "w") do |f|
    f.puts "% This file has been generated by " + $0 
    f.puts "% Only changes to the \"misc\" column will be saved."
    f.puts "% % Syntax:"
    f.puts "% \\skill{Name}{ability}{ranks}{misc}{class}{trained_only}"
    f.puts "% Where class is 1 for a class skill and 0 for cross-class"
    f.puts "% eg: \\skill{Bluff}{Cha}{2}{0}{1}{0}"
    h.each_value.sort_by{ |s| s[:name]}.each do |v| 
      f.puts "\\skill{" + v[:name] + "}\t\t{" + v[:ability] + "}{" + v[:ranks] + "}{" + v[:misc] + "}{" + v[:class] + "}{" + v[:trained_only] + "}"
    end
  end

       
end       

